/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, { Component } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import CarefreeSearchAmap from 'carefree-search-amap-react-native';

export default class App extends Component {
  state = {
    status: 'starting',
    message: '--',
  };
  async componentDidMount() {
    try {
      const result = await CarefreeSearchAmap.initSDK('07976cdaf75c89e7a455f8dd3f3ec56e');
      console.log('res', result);
      const result2 = await CarefreeSearchAmap.getLatlong('上海市青浦区e通世界北区');
      console.log("result2", result2)
      const result3 = await CarefreeSearchAmap.getAddress(result2);
      console.log("result3", result3)
      // console.log('CarefreeSearchAmap', CarefreeSearchAmap);
    } catch (err) {
      console.log('错误信息----》', err)
    }
  }
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>☆CarefreeSearchAmap example☆</Text>
        <Text style={styles.instructions}>STATUS: {this.state.status}</Text>
        <Text style={styles.welcome}>☆NATIVE CALLBACK MESSAGE☆</Text>
        <Text style={styles.instructions}>{this.state.message}</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
